# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/detector.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/detector.proto\x12\x06protos\"B\n\rDetectRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\"h\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\"K\n\x0e\x44\x65tectResponse\x12%\n\ndetections\x18\x01 \x03(\x0b\x32\x11.protos.Detection\x12\x12\n\nlatency_ms\x18\x02 \x01(\x01\x32J\n\x0f\x44\x65tectorService\x12\x37\n\x06\x44\x65tect\x12\x15.protos.DetectRequest\x1a\x16.protos.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=33
  _globals['_DETECTREQUEST']._serialized_end=99
  _globals['_DETECTION']._serialized_start=101
  _globals['_DETECTION']._serialized_end=205
  _globals['_DETECTRESPONSE']._serialized_start=207
  _globals['_DETECTRESPONSE']._serialized_end=282
  _globals['_DETECTORSERVICE']._serialized_start=284
  _globals['_DETECTORSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
